### ISSUE TITLE
Feature Request: add user setting enabling user to set different image storage folder?

### ISSUE THREAD

**Issue by StoneBlue** [linuxgurugamer/ksp-img_viewer#3]
LGG, just wondering if it would be a lot of trouble to add a setting for users to change/set their own image storage directory?

Use case, for me at least, is quite often forgetting to copy/paste my image storage folder when removing/doing a fresh install of the mod, and I end up losing everything.

I like to use this mod to view documentation .pdfs and images that lots of mods include.
Saves me from having to open external viewers for various formats, of course.

But i tend to gather quite a collection, and when forgetting to grab the folder out of the mod directory, its quite a pain to try to rebuild the collection. :P 

I usually create my own /GameData/zStoneBlue/ folder for keeping my custom MM patches in, and/or any other custom stuff I do that generally I like to keep, when adding/deleting/updating mods. Would be awesome if I could store my images for use with Image Viewer there.
(Also would be nice if the Notes mod offered this same feature :P ... I posted in Agises Notes thread asking wht he thought of adding this feature.)

Adding this feature might help people who dont do manual mod installing, and use CKAN-only... vOv
I assume CKAN will just overwrite/delete all the mod folders, but leave the storage folder untouched on a mod update or mod removal? vOv

Thanx for maintaining this mod. i for one find it HIGHLY useful. ;)

**Comment by linuxgurugamer** [comment]
I assume that a line in a cfg file would suffice for now?

**Comment by linuxgurugamer** [comment]
> Adding this feature might help people who dont do manual mod installing, and use CKAN-only... vOv
I assume CKAN will just overwrite/delete all the mod folders, but leave the storage folder untouched on a mod update or mod removal? vOv

You are correct

**Comment by linuxgurugamer** [comment]
Just updated, see the changelog in the post

**Comment by StoneBlue** [comment]
Thank You! :D
